### ISSUE TITLE
Instructions to run it locally (Linux)

### ISSUE THREAD

**Issue by afkcodes** [clausecker/24puzzle#1]
Hey thanks for such a wonderful work i was looking to generate some puzzles for a dun project i was doing but it seems to not run on my machine please add an instruction to set it up on local machine.

I tried running make but failed with an error this error popped up
```
~/24puzzle -> master !
❯ make
CC	cmd/pdbstats.c
make: clang: No such file or directory
make: *** [Makefile:85: cmd/pdbstats.o] Error 127
```

also tried running the shell script gave this error
```
1 ❯ sudo ./genallpdbs.sh 
[sudo] password for ashish: 
2021-03-21 01:31:39: Generating all PDBs for 6 tiles to /local/bzcclaus/scratch/pdbs
./genallpdbs.sh: line 49: pdbcount: command not found
./genallpdbs.sh: line 28: genpdb: command not found
```

Any help will be appreciated

**Comment by clausecker** [comment]
You may need to set the environment variable `CC` to point to a C compiler.  This usually works:

    make CC=cc

Please do not run any of the programs or scripts in the project with elevated privileges (i.e. using `sudo`).  There is nothing in there that requires that and it's a potential risk in case I made a programming error.  I don't think you have any need to run `genallpdbs.sh` anyway; this script generates over 160 GB of data and takes several days to complete.  The search programs generate the pattern databases they need whenever they need them, so there's no need to generate all PDBs ahead of time.

If you'll let me know what exactly you are trying to achieve, I may be able to give more specific help.  If you want to generate puzzle instances, use `cmd/puzzlegen`.  But note that as of now, this program is likely to generate unsolvably hard puzzle instances.  I have not implemented logic to support generation of “easy” instances on command, though I suppose such a thing should be easy to add if desired.

**Comment by afkcodes** [comment]
Thanks for detailed information, my basic requirement is to create a game out of these and as you suggested now that the puzzlegen script does not create easy levels i would love to see 4 difficulty levels if possible
namely 

1. Easy
2. Medium
3. Difficult
4. Insane

**Comment by afkcodes** [comment]
also if one configuration to generate multiple files at once like if i want to generate 100 puzzles of easy  or 
n puzzles of  Medium. I don't know how much effort it is from your side a help would make this repo a playable game.

**Comment by clausecker** [comment]
What is your criterion for considering a puzzle “easy,” “medium,” “difficult,” or “insane?”  Sliding tile puzzles are always rather easy to solve for humans.  The thing that is hard is solving them with the minimal amount of moves needed and humans are really bad at that.

**Comment by afkcodes** [comment]
got it so basically we can adjust the difficulty by something called shuffle factor which will determine how strongly the matrix would be shiuffled, i don't whether im correct jere or not but the more randomised the matrix is the more it will be difficult to solve in my opinion.

also an option to generate 4x4, 5x5, 6x6 7x7 would be awesome.

**Comment by clausecker** [comment]
The code in this repository is for 5x5 puzzles only.  I am not sure what this “shuffle factor” is supposed to be exactly.  A simple way to generate random puzzles with an adjustable amount of “shuffledness” is to start with the solved puzzle and then perform a sequence of random moves.  The more moves you do, the more shuffled the puzzle ends up being.  This allows you to generate puzzles up to a difficulty of around 140 moves.  Above that, it's difficult to intentionally find harder puzzles.

I recommend you try implementing that yourself.  It's really not hard to do.  And after all, it's going to be your game, so I don't see why I should do the programming work for you.
